- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /5g
    state: "directory"
  become: yes

- name: Copy oai-5g-core.tar.gz to the target host
  ansible.builtin.copy:
    src: oai-5g-core.tar.gz
    dest: /5g/oai-5g-core.tar.gz
  become: yes

- name: Extract files from oai-5g-core.tar.gz
  ansible.builtin.unarchive:
    src: /5g/oai-5g-core.tar.gz
    dest: /5g
    remote_src: true
  become: yes

- name: Update Helm dependencies
  command: helm dependency update
  args:
    chdir: /5g/oai-5g-core/oai-5g-basic

- name: Install Helm chart
  command: helm install oai-core /5g/oai-5g-core/oai-5g-basic

- name: Fetch status of all pods
  kubernetes.core.k8s_info:
    kind: Pod
    kubeconfig: .kube/config
  register: pod_info

- name: Attendre que tous les pods soient en cours d'exécution
  shell: >
    kubectl get pods --kubeconfig .kube/config --field-selector=status.phase!=Running -o jsonpath='{.items[*].metadata.name}'
  register: not_running_pods
  until: not_running_pods.stdout_lines | length == 0
  retries: 30
  delay: 10
  changed_when: false
    
