- name: Update Helm dependencies
  become: yes
  command: helm dependency update
  args:
    chdir: /5g/oai-5g-core/oai-5g-basic  # Chemin vers le répertoire contenant votre chart Helm

- name: Install Helm chart
  command: helm install oai-core /5g/oai-5g-core/oai-5g-basic

