- name: Extract oai-nr-ue.tar.gz and oai-gnb.tar.gz files
  become: yes
  ansible.builtin.unarchive:
    src: oai-nr-ue.tar.gz
    dest: /5g/oai-nr-ue
    remote_src: yes

- name: Extract oai-gnb.tar.gz file
  become: yes
  ansible.builtin.unarchive:
    src: oai-gnb.tar.gz
    dest: /5g/oai-gnb
    remote_src: yes

- name: Install oai-gnb Helm chart
  command: helm install oai-gnb .
  args:
    chdir: /5g/oai-gnb

- name: Install oai-nr-ue Helm chart
  command: helm install oai-nr-ue .
  args:
    chdir: /5g/oai-nr-ue


