
- name: Copy oai-nr-ue.tar.gz to the target host
  ansible.builtin.copy:
    src: oai-nr-ue.tar.gz
    dest: /5g/oai-nr-ue.tar.gz
  become: yes

- name: Copy oai-gnb.tar.gz to the target host
  ansible.builtin.copy:
    src: oai-gnb.tar.gz
    dest: /5g/oai-gnb.tar.gz
  become: yes

- name: Extract oai-nr-ue.tar.gz and oai-gnb.tar.gz files
  become: yes
  ansible.builtin.unarchive:
    src: oai-nr-ue.tar.gz
    dest: /5g
    remote_src: false

- name: Extract oai-gnb.tar.gz file
  become: yes
  ansible.builtin.unarchive:
    src: oai-gnb.tar.gz
    dest: /5g
    remote_src: false

- name: Install oai-gnb Helm chart
  command: helm install oai-gnb .
  args:
    chdir: /5g/oai-gnb

      #- name: Install oai-nr-ue Helm chart
      #command: helm install oai-nr-ue .
      #args:
      #chdir: /5g/oai-nr-ue


