
- name: Check if Helm is installed
  command: which helm
  register: helm_check
  failed_when: false
  changed_when: false

- name: Install dependencies
  apt:
    name: 
      - curl
    state: present
  when: helm_check.rc != 0

- name: Download Helm
  get_url:
    url: "https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz"
    dest: "/tmp/helm-v3.7.0-linux-amd64.tar.gz"
    mode: '0644'
  when: helm_check.rc != 0

- name: Extract Helm tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/helm-v3.7.0-linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: helm_check.rc != 0

- name: Move Helm to /usr/local/bin
  become: yes
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  args:
    creates: "/usr/local/bin/helm"
  when: helm_check.rc != 0

- name: Verify Helm installation (for new installations)
  command: helm version
  register: helm_version_output
  when: helm_check.rc != 0

- name: Show Helm version (for new installations)
  debug:
    msg: "{{ helm_version_output.stdout }}"
  when: helm_check.rc != 0

- name: Install Helm spray plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/ThalesGroup/helm-spray
    plugin_version: v4.0.10
    state: present

