- name: Copy the 'cri-dockerd' archive.
  copy:
    src: cri-dockerd.tar.gz
    dest: /install/ 
  
- name: Extract the cri-dockerd archive.
  unarchive:
    src: /install/cri-dockerd.tar.gz
    dest: /install/
    creates: /install/cri-dockerd 
    remote_src: yes

- name: Install the 'make' package.
  apt:
    name: make
    state: present
  become: yes

- name: Copy Go archive.
  copy:
    src: go1.22.1.linux-amd64.tar.gz
    dest: /tmp/

- name: Extract the Go archive.
  unarchive:
    src: /tmp/go1.22.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
  become: yes

- name: Execute the command 'make cri-dockerd'.
  command: make cri-dockerd
  args:
    chdir: /install/cri-dockerd
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

- name: Copy the 'cri-dockerd' file to /usr/local/bin.
  copy:
    src: /install/cri-dockerd/
    dest: /usr/local/bin/
    remote_src: true

  
- name: Copy the systemd files to /etc/systemd/system.
  copy: 
    src: /install/cri-dockerd/packaging/systemd/ 
    dest: /etc/systemd/system/
    remote_src: true

- name: Replace the path in the cri-docker.service file.
  replace:
    path: /etc/systemd/system/cri-docker.service
    regexp: '/usr/bin/cri-dockerd'
    replace: '/usr/local/bin/cri-dockerd'

- name: Reload the systemd daemon.
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start the cri-docker socket.
  systemd:
    name: cri-docker.socket
    enabled: yes
    state: started
  become: yes

- name: Enable and start the cri-docker service.
  systemd:
    name: cri-docker.service
    enabled: yes
    state: started
  become: yes

- name: Ensure cri-dockerd is restarted and running
  systemd:
    name: cri-docker.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Wait for cri-dockerd to be ready
  wait_for:
    path: /var/run/cri-dockerd.sock
    state: present
    timeout: 30



